### ISSUE TITLE
Warning: Unexpected input(s) 'shell', valid inputs are ['dest']

### ISSUE THREAD

**Issue by ochanje210** [jwalton/gh-docker-logs#14]
I simply tried with dumping docker logs using different shell with the following step:
```yml
- name: Dump docker logs using different shell
        uses: jwalton/gh-docker-logs@v1
        with:
          shell: '/bin/sh'
```
However, I'm having the following warning from my workflow:

![Screen Shot 2022-08-03 at 4 08 08 PM](https://user-images.githubusercontent.com/16204807/182699534-2e652205-8532-48ac-a74d-cad250291395.png)
